services:
  - type: web
    name: propulsor-journey
    runtime: docker
    plan: free
    region: ohio
    envVars:
      - key: NODE_VERSION
        value: 18.16.0
      - key: PUPPETEER_SKIP_CHROMIUM_DOWNLOAD
        value: "true"
      - key: PUPPETEER_EXECUTABLE_PATH
        value: /usr/bin/google-chrome-stable
